---

db_host: "{{ hostvars[groups['role_db'][0]].private_ip }}"
db_name: appdb
db_user: appuser

db_pass: "AppPass123!"

db_root_pass: "{{ db_pass }}_root"

# PHP-FPM pool
php_fpm_pool_user:  nginx
php_fpm_pool_group: nginx
php_fpm_socket:     /run/php-fpm/www.sock

# Web root served by nginx and populated by roles/php_app
web_root: /var/www/html
