---

- name: Common baseline on all hosts
  hosts: all
  gather_facts: false
  become: true
  become_method: sudo
  roles:
    - common
  tags:
    - common

- name: Database server
  hosts: role_db
  gather_facts: true
  become: true
  become_method: sudo
  vars_files:
    - inventory/group_vars/web.yml
  vars:
    db_root_pass: "{{ db_pass }}_root"
  roles:
    - mariadb
  tags:
    - db
    - mariadb

- name: Web servers (Nginx + PHP-FPM + app)
  hosts: web
  gather_facts: false
  become: true
  become_method: sudo
  roles:
    - nginx
    - php_app
  tags:
    - web

- name: HAProxy load balancer
  hosts: role_haproxy
  gather_facts: false
  become: true
  become_method: sudo
  roles:
    - haproxy
  tags:
    - haproxy
    - lb
